[package]
name = "mbus-codec"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.10.1"
mbus-protocol = { path = "../mbus-protocol" }
tokio-util = { version = "0.7.13", features = ["codec"] }
tracing = "0.1.41"
